//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvokeWCFTest.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TemplateTagDataCollection", Namespace="http://schemas.datacontract.org/2004/07/com.eLong.Template.Model")]
    [System.SerializableAttribute()]
    public partial class TemplateTagDataCollection : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, InvokeWCFTest.ServiceReference1.TemplateTagData> DictionaryField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, InvokeWCFTest.ServiceReference1.TemplateTagData> Dictionary {
            get {
                return this.DictionaryField;
            }
            set {
                if ((object.ReferenceEquals(this.DictionaryField, value) != true)) {
                    this.DictionaryField = value;
                    this.RaisePropertyChanged("Dictionary");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TemplateTagData", Namespace="http://schemas.datacontract.org/2004/07/com.eLong.Template.Model")]
    [System.SerializableAttribute()]
    public partial class TemplateTagData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private InvokeWCFTest.ServiceReference1.TemplateTagDataCollection[] ChildTagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TagKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TagValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public InvokeWCFTest.ServiceReference1.TemplateTagDataCollection[] ChildTag {
            get {
                return this.ChildTagField;
            }
            set {
                if ((object.ReferenceEquals(this.ChildTagField, value) != true)) {
                    this.ChildTagField = value;
                    this.RaisePropertyChanged("ChildTag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TagKey {
            get {
                return this.TagKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.TagKeyField, value) != true)) {
                    this.TagKeyField = value;
                    this.RaisePropertyChanged("TagKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TagValue {
            get {
                return this.TagValueField;
            }
            set {
                if ((object.ReferenceEquals(this.TagValueField, value) != true)) {
                    this.TagValueField = value;
                    this.RaisePropertyChanged("TagValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Response", Namespace="http://schemas.datacontract.org/2004/07/com.eLong.Template.Model")]
    [System.SerializableAttribute()]
    public partial class Response : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] documentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private InvokeWCFTest.ServiceReference1.EnumResponseCode EnumResponseCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] document {
            get {
                return this.documentField;
            }
            set {
                if ((object.ReferenceEquals(this.documentField, value) != true)) {
                    this.documentField = value;
                    this.RaisePropertyChanged("document");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public InvokeWCFTest.ServiceReference1.EnumResponseCode EnumResponseCode {
            get {
                return this.EnumResponseCodeField;
            }
            set {
                if ((this.EnumResponseCodeField.Equals(value) != true)) {
                    this.EnumResponseCodeField = value;
                    this.RaisePropertyChanged("EnumResponseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string ResponseMessage {
            get {
                return this.ResponseMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseMessageField, value) != true)) {
                    this.ResponseMessageField = value;
                    this.RaisePropertyChanged("ResponseMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorCodeField, value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnumResponseCode", Namespace="http://schemas.datacontract.org/2004/07/com.eLong.Template.Model")]
    public enum EnumResponseCode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Fail = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TemplateInfo", Namespace="http://schemas.datacontract.org/2004/07/com.eLong.Template.Model")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InvokeWCFTest.ServiceReference1.TemplateTagDataCollection))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InvokeWCFTest.ServiceReference1.TemplateTagData))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InvokeWCFTest.ServiceReference1.TemplateTagDataCollection[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InvokeWCFTest.ServiceReference1.Response))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InvokeWCFTest.ServiceReference1.EnumResponseCode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InvokeWCFTest.ServiceReference1.OperateInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InvokeWCFTest.ServiceReference1.ProductType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InvokeWCFTest.ServiceReference1.TemplateStatus))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InvokeWCFTest.ServiceReference1.TemplateTagInfo[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InvokeWCFTest.ServiceReference1.TemplateTagInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InvokeWCFTest.ServiceReference1.DataState))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InvokeWCFTest.ServiceReference1.TagSource))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InvokeWCFTest.ServiceReference1.TemplateTagType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InvokeWCFTest.ServiceReference1.TemplateType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(InvokeWCFTest.ServiceReference1.TemplateInfo[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, InvokeWCFTest.ServiceReference1.TemplateTagData>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(string[]))]
    public partial class TemplateInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private InvokeWCFTest.ServiceReference1.OperateInfo ChangeOperateInfok__BackingFieldField;
        
        private string Documentk__BackingFieldField;
        
        private string Namek__BackingFieldField;
        
        private InvokeWCFTest.ServiceReference1.ProductType ProductTypek__BackingFieldField;
        
        private string Remarkk__BackingFieldField;
        
        private InvokeWCFTest.ServiceReference1.TemplateStatus Statusk__BackingFieldField;
        
        private object SubjectTemplateContentk__BackingFieldField;
        
        private string Subjectk__BackingFieldField;
        
        private object TemplateContentk__BackingFieldField;
        
        private System.Guid TemplateIDk__BackingFieldField;
        
        private string TemplateNOk__BackingFieldField;
        
        private InvokeWCFTest.ServiceReference1.TemplateTagInfo[] TemplateTagsk__BackingFieldField;
        
        private string Templatek__BackingFieldField;
        
        private InvokeWCFTest.ServiceReference1.TemplateType Typek__BackingFieldField;
        
        private int WordCountk__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ChangeOperateInfo>k__BackingField", IsRequired=true)]
        public InvokeWCFTest.ServiceReference1.OperateInfo ChangeOperateInfok__BackingField {
            get {
                return this.ChangeOperateInfok__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.ChangeOperateInfok__BackingFieldField, value) != true)) {
                    this.ChangeOperateInfok__BackingFieldField = value;
                    this.RaisePropertyChanged("ChangeOperateInfok__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Document>k__BackingField", IsRequired=true)]
        public string Documentk__BackingField {
            get {
                return this.Documentk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Documentk__BackingFieldField, value) != true)) {
                    this.Documentk__BackingFieldField = value;
                    this.RaisePropertyChanged("Documentk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Name>k__BackingField", IsRequired=true)]
        public string Namek__BackingField {
            get {
                return this.Namek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Namek__BackingFieldField, value) != true)) {
                    this.Namek__BackingFieldField = value;
                    this.RaisePropertyChanged("Namek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ProductType>k__BackingField", IsRequired=true)]
        public InvokeWCFTest.ServiceReference1.ProductType ProductTypek__BackingField {
            get {
                return this.ProductTypek__BackingFieldField;
            }
            set {
                if ((this.ProductTypek__BackingFieldField.Equals(value) != true)) {
                    this.ProductTypek__BackingFieldField = value;
                    this.RaisePropertyChanged("ProductTypek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Remark>k__BackingField", IsRequired=true)]
        public string Remarkk__BackingField {
            get {
                return this.Remarkk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Remarkk__BackingFieldField, value) != true)) {
                    this.Remarkk__BackingFieldField = value;
                    this.RaisePropertyChanged("Remarkk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Status>k__BackingField", IsRequired=true)]
        public InvokeWCFTest.ServiceReference1.TemplateStatus Statusk__BackingField {
            get {
                return this.Statusk__BackingFieldField;
            }
            set {
                if ((this.Statusk__BackingFieldField.Equals(value) != true)) {
                    this.Statusk__BackingFieldField = value;
                    this.RaisePropertyChanged("Statusk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<SubjectTemplateContent>k__BackingField", IsRequired=true)]
        public object SubjectTemplateContentk__BackingField {
            get {
                return this.SubjectTemplateContentk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.SubjectTemplateContentk__BackingFieldField, value) != true)) {
                    this.SubjectTemplateContentk__BackingFieldField = value;
                    this.RaisePropertyChanged("SubjectTemplateContentk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Subject>k__BackingField", IsRequired=true)]
        public string Subjectk__BackingField {
            get {
                return this.Subjectk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Subjectk__BackingFieldField, value) != true)) {
                    this.Subjectk__BackingFieldField = value;
                    this.RaisePropertyChanged("Subjectk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<TemplateContent>k__BackingField", IsRequired=true)]
        public object TemplateContentk__BackingField {
            get {
                return this.TemplateContentk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.TemplateContentk__BackingFieldField, value) != true)) {
                    this.TemplateContentk__BackingFieldField = value;
                    this.RaisePropertyChanged("TemplateContentk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<TemplateID>k__BackingField", IsRequired=true)]
        public System.Guid TemplateIDk__BackingField {
            get {
                return this.TemplateIDk__BackingFieldField;
            }
            set {
                if ((this.TemplateIDk__BackingFieldField.Equals(value) != true)) {
                    this.TemplateIDk__BackingFieldField = value;
                    this.RaisePropertyChanged("TemplateIDk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<TemplateNO>k__BackingField", IsRequired=true)]
        public string TemplateNOk__BackingField {
            get {
                return this.TemplateNOk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.TemplateNOk__BackingFieldField, value) != true)) {
                    this.TemplateNOk__BackingFieldField = value;
                    this.RaisePropertyChanged("TemplateNOk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<TemplateTags>k__BackingField", IsRequired=true)]
        public InvokeWCFTest.ServiceReference1.TemplateTagInfo[] TemplateTagsk__BackingField {
            get {
                return this.TemplateTagsk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.TemplateTagsk__BackingFieldField, value) != true)) {
                    this.TemplateTagsk__BackingFieldField = value;
                    this.RaisePropertyChanged("TemplateTagsk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Template>k__BackingField", IsRequired=true)]
        public string Templatek__BackingField {
            get {
                return this.Templatek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Templatek__BackingFieldField, value) != true)) {
                    this.Templatek__BackingFieldField = value;
                    this.RaisePropertyChanged("Templatek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Type>k__BackingField", IsRequired=true)]
        public InvokeWCFTest.ServiceReference1.TemplateType Typek__BackingField {
            get {
                return this.Typek__BackingFieldField;
            }
            set {
                if ((this.Typek__BackingFieldField.Equals(value) != true)) {
                    this.Typek__BackingFieldField = value;
                    this.RaisePropertyChanged("Typek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<WordCount>k__BackingField", IsRequired=true)]
        public int WordCountk__BackingField {
            get {
                return this.WordCountk__BackingFieldField;
            }
            set {
                if ((this.WordCountk__BackingFieldField.Equals(value) != true)) {
                    this.WordCountk__BackingFieldField = value;
                    this.RaisePropertyChanged("WordCountk__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperateInfo", Namespace="http://schemas.datacontract.org/2004/07/com.eLong.Template.Model")]
    [System.SerializableAttribute()]
    public partial class OperateInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OperatorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OperatorIPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime OperatorTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Operator {
            get {
                return this.OperatorField;
            }
            set {
                if ((object.ReferenceEquals(this.OperatorField, value) != true)) {
                    this.OperatorField = value;
                    this.RaisePropertyChanged("Operator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OperatorIP {
            get {
                return this.OperatorIPField;
            }
            set {
                if ((object.ReferenceEquals(this.OperatorIPField, value) != true)) {
                    this.OperatorIPField = value;
                    this.RaisePropertyChanged("OperatorIP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime OperatorTime {
            get {
                return this.OperatorTimeField;
            }
            set {
                if ((this.OperatorTimeField.Equals(value) != true)) {
                    this.OperatorTimeField = value;
                    this.RaisePropertyChanged("OperatorTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.FlagsAttribute()]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductType", Namespace="http://schemas.datacontract.org/2004/07/com.eLong.Template.Model")]
    public enum ProductType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Hotel = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Air = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CRM = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TemplateStatus", Namespace="http://schemas.datacontract.org/2004/07/com.eLong.Template.Model")]
    public enum TemplateStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Edit = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Release = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TemplateTagInfo", Namespace="http://schemas.datacontract.org/2004/07/com.eLong.Template.Model")]
    [System.SerializableAttribute()]
    public partial class TemplateTagInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private InvokeWCFTest.ServiceReference1.OperateInfo ChangeOperateInfok__BackingFieldField;
        
        private InvokeWCFTest.ServiceReference1.DataState DataStatek__BackingFieldField;
        
        private int OrderNumberk__BackingFieldField;
        
        private System.Nullable<System.Guid> ParentIDk__BackingFieldField;
        
        private string ParentTagk__BackingFieldField;
        
        private string Remarkk__BackingFieldField;
        
        private InvokeWCFTest.ServiceReference1.TagSource Sourcek__BackingFieldField;
        
        private string TagNamek__BackingFieldField;
        
        private string Tagk__BackingFieldField;
        
        private System.Guid TemplateIDk__BackingFieldField;
        
        private System.Guid TemplateTagIDk__BackingFieldField;
        
        private string TestDatak__BackingFieldField;
        
        private InvokeWCFTest.ServiceReference1.TemplateTagType Typek__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ChangeOperateInfo>k__BackingField", IsRequired=true)]
        public InvokeWCFTest.ServiceReference1.OperateInfo ChangeOperateInfok__BackingField {
            get {
                return this.ChangeOperateInfok__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.ChangeOperateInfok__BackingFieldField, value) != true)) {
                    this.ChangeOperateInfok__BackingFieldField = value;
                    this.RaisePropertyChanged("ChangeOperateInfok__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<DataState>k__BackingField", IsRequired=true)]
        public InvokeWCFTest.ServiceReference1.DataState DataStatek__BackingField {
            get {
                return this.DataStatek__BackingFieldField;
            }
            set {
                if ((this.DataStatek__BackingFieldField.Equals(value) != true)) {
                    this.DataStatek__BackingFieldField = value;
                    this.RaisePropertyChanged("DataStatek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<OrderNumber>k__BackingField", IsRequired=true)]
        public int OrderNumberk__BackingField {
            get {
                return this.OrderNumberk__BackingFieldField;
            }
            set {
                if ((this.OrderNumberk__BackingFieldField.Equals(value) != true)) {
                    this.OrderNumberk__BackingFieldField = value;
                    this.RaisePropertyChanged("OrderNumberk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ParentID>k__BackingField", IsRequired=true)]
        public System.Nullable<System.Guid> ParentIDk__BackingField {
            get {
                return this.ParentIDk__BackingFieldField;
            }
            set {
                if ((this.ParentIDk__BackingFieldField.Equals(value) != true)) {
                    this.ParentIDk__BackingFieldField = value;
                    this.RaisePropertyChanged("ParentIDk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ParentTag>k__BackingField", IsRequired=true)]
        public string ParentTagk__BackingField {
            get {
                return this.ParentTagk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.ParentTagk__BackingFieldField, value) != true)) {
                    this.ParentTagk__BackingFieldField = value;
                    this.RaisePropertyChanged("ParentTagk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Remark>k__BackingField", IsRequired=true)]
        public string Remarkk__BackingField {
            get {
                return this.Remarkk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Remarkk__BackingFieldField, value) != true)) {
                    this.Remarkk__BackingFieldField = value;
                    this.RaisePropertyChanged("Remarkk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Source>k__BackingField", IsRequired=true)]
        public InvokeWCFTest.ServiceReference1.TagSource Sourcek__BackingField {
            get {
                return this.Sourcek__BackingFieldField;
            }
            set {
                if ((this.Sourcek__BackingFieldField.Equals(value) != true)) {
                    this.Sourcek__BackingFieldField = value;
                    this.RaisePropertyChanged("Sourcek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<TagName>k__BackingField", IsRequired=true)]
        public string TagNamek__BackingField {
            get {
                return this.TagNamek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.TagNamek__BackingFieldField, value) != true)) {
                    this.TagNamek__BackingFieldField = value;
                    this.RaisePropertyChanged("TagNamek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Tag>k__BackingField", IsRequired=true)]
        public string Tagk__BackingField {
            get {
                return this.Tagk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Tagk__BackingFieldField, value) != true)) {
                    this.Tagk__BackingFieldField = value;
                    this.RaisePropertyChanged("Tagk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<TemplateID>k__BackingField", IsRequired=true)]
        public System.Guid TemplateIDk__BackingField {
            get {
                return this.TemplateIDk__BackingFieldField;
            }
            set {
                if ((this.TemplateIDk__BackingFieldField.Equals(value) != true)) {
                    this.TemplateIDk__BackingFieldField = value;
                    this.RaisePropertyChanged("TemplateIDk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<TemplateTagID>k__BackingField", IsRequired=true)]
        public System.Guid TemplateTagIDk__BackingField {
            get {
                return this.TemplateTagIDk__BackingFieldField;
            }
            set {
                if ((this.TemplateTagIDk__BackingFieldField.Equals(value) != true)) {
                    this.TemplateTagIDk__BackingFieldField = value;
                    this.RaisePropertyChanged("TemplateTagIDk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<TestData>k__BackingField", IsRequired=true)]
        public string TestDatak__BackingField {
            get {
                return this.TestDatak__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.TestDatak__BackingFieldField, value) != true)) {
                    this.TestDatak__BackingFieldField = value;
                    this.RaisePropertyChanged("TestDatak__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Type>k__BackingField", IsRequired=true)]
        public InvokeWCFTest.ServiceReference1.TemplateTagType Typek__BackingField {
            get {
                return this.Typek__BackingFieldField;
            }
            set {
                if ((this.Typek__BackingFieldField.Equals(value) != true)) {
                    this.Typek__BackingFieldField = value;
                    this.RaisePropertyChanged("Typek__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataState", Namespace="http://schemas.datacontract.org/2004/07/com.eLong.Template.Model")]
    public enum DataState : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unchanged = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Added = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Deleted = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Modified = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.FlagsAttribute()]
    [System.Runtime.Serialization.DataContractAttribute(Name="TagSource", Namespace="http://schemas.datacontract.org/2004/07/com.eLong.Template.Model")]
    public enum TagSource : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Body = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Subject = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TemplateTagType", Namespace="http://schemas.datacontract.org/2004/07/com.eLong.Template.Model")]
    public enum TemplateTagType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Field = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Table = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Logic = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TemplateType", Namespace="http://schemas.datacontract.org/2004/07/com.eLong.Template.Model")]
    public enum TemplateType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SMS = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EMail = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Fax = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="com.eLong.TemplateService", ConfigurationName="ServiceReference1.ITemplateWebservice")]
    public interface ITemplateWebservice {
        
        [System.ServiceModel.OperationContractAttribute(Action="com.eLong.TemplateService/ITemplateWebservice/GetTemplate", ReplyAction="com.eLong.TemplateService/ITemplateWebservice/GetTemplateResponse")]
        InvokeWCFTest.ServiceReference1.Response GetTemplate(string templateNo, InvokeWCFTest.ServiceReference1.TemplateTagDataCollection tagDatas);
        
        [System.ServiceModel.OperationContractAttribute(Action="com.eLong.TemplateService/ITemplateWebservice/GetTemplate", ReplyAction="com.eLong.TemplateService/ITemplateWebservice/GetTemplateResponse")]
        System.Threading.Tasks.Task<InvokeWCFTest.ServiceReference1.Response> GetTemplateAsync(string templateNo, InvokeWCFTest.ServiceReference1.TemplateTagDataCollection tagDatas);
        
        [System.ServiceModel.OperationContractAttribute(Action="com.eLong.TemplateService/ITemplateWebservice/GetTemplateInfo", ReplyAction="com.eLong.TemplateService/ITemplateWebservice/GetTemplateInfoResponse")]
        InvokeWCFTest.ServiceReference1.GetTemplateInfoResponse GetTemplateInfo(InvokeWCFTest.ServiceReference1.GetTemplateInfoRequest request);
        
        // CODEGEN: 正在生成消息协定，应为该操作具有多个返回值。
        [System.ServiceModel.OperationContractAttribute(Action="com.eLong.TemplateService/ITemplateWebservice/GetTemplateInfo", ReplyAction="com.eLong.TemplateService/ITemplateWebservice/GetTemplateInfoResponse")]
        System.Threading.Tasks.Task<InvokeWCFTest.ServiceReference1.GetTemplateInfoResponse> GetTemplateInfoAsync(InvokeWCFTest.ServiceReference1.GetTemplateInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="com.eLong.TemplateService/ITemplateWebservice/GetTemplateList", ReplyAction="com.eLong.TemplateService/ITemplateWebservice/GetTemplateListResponse")]
        InvokeWCFTest.ServiceReference1.GetTemplateListResponse GetTemplateList(InvokeWCFTest.ServiceReference1.GetTemplateListRequest request);
        
        // CODEGEN: 正在生成消息协定，应为该操作具有多个返回值。
        [System.ServiceModel.OperationContractAttribute(Action="com.eLong.TemplateService/ITemplateWebservice/GetTemplateList", ReplyAction="com.eLong.TemplateService/ITemplateWebservice/GetTemplateListResponse")]
        System.Threading.Tasks.Task<InvokeWCFTest.ServiceReference1.GetTemplateListResponse> GetTemplateListAsync(InvokeWCFTest.ServiceReference1.GetTemplateListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="com.eLong.TemplateService/ITemplateWebservice/Ping", ReplyAction="com.eLong.TemplateService/ITemplateWebservice/PingResponse")]
        bool Ping();
        
        [System.ServiceModel.OperationContractAttribute(Action="com.eLong.TemplateService/ITemplateWebservice/Ping", ReplyAction="com.eLong.TemplateService/ITemplateWebservice/PingResponse")]
        System.Threading.Tasks.Task<bool> PingAsync();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTemplateInfo", WrapperNamespace="com.eLong.TemplateService", IsWrapped=true)]
    public partial class GetTemplateInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.eLong.TemplateService", Order=0)]
        public string templateNo;
        
        public GetTemplateInfoRequest() {
        }
        
        public GetTemplateInfoRequest(string templateNo) {
            this.templateNo = templateNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTemplateInfoResponse", WrapperNamespace="com.eLong.TemplateService", IsWrapped=true)]
    public partial class GetTemplateInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.eLong.TemplateService", Order=0)]
        public InvokeWCFTest.ServiceReference1.Response GetTemplateInfoResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.eLong.TemplateService", Order=1)]
        public InvokeWCFTest.ServiceReference1.TemplateInfo templateInfo;
        
        public GetTemplateInfoResponse() {
        }
        
        public GetTemplateInfoResponse(InvokeWCFTest.ServiceReference1.Response GetTemplateInfoResult, InvokeWCFTest.ServiceReference1.TemplateInfo templateInfo) {
            this.GetTemplateInfoResult = GetTemplateInfoResult;
            this.templateInfo = templateInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTemplateList", WrapperNamespace="com.eLong.TemplateService", IsWrapped=true)]
    public partial class GetTemplateListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.eLong.TemplateService", Order=0)]
        public InvokeWCFTest.ServiceReference1.ProductType productType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.eLong.TemplateService", Order=1)]
        public InvokeWCFTest.ServiceReference1.TemplateType templateType;
        
        public GetTemplateListRequest() {
        }
        
        public GetTemplateListRequest(InvokeWCFTest.ServiceReference1.ProductType productType, InvokeWCFTest.ServiceReference1.TemplateType templateType) {
            this.productType = productType;
            this.templateType = templateType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTemplateListResponse", WrapperNamespace="com.eLong.TemplateService", IsWrapped=true)]
    public partial class GetTemplateListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.eLong.TemplateService", Order=0)]
        public InvokeWCFTest.ServiceReference1.Response GetTemplateListResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.eLong.TemplateService", Order=1)]
        public InvokeWCFTest.ServiceReference1.TemplateInfo[] templateInfos;
        
        public GetTemplateListResponse() {
        }
        
        public GetTemplateListResponse(InvokeWCFTest.ServiceReference1.Response GetTemplateListResult, InvokeWCFTest.ServiceReference1.TemplateInfo[] templateInfos) {
            this.GetTemplateListResult = GetTemplateListResult;
            this.templateInfos = templateInfos;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITemplateWebserviceChannel : InvokeWCFTest.ServiceReference1.ITemplateWebservice, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TemplateWebserviceClient : System.ServiceModel.ClientBase<InvokeWCFTest.ServiceReference1.ITemplateWebservice>, InvokeWCFTest.ServiceReference1.ITemplateWebservice {
        
        public TemplateWebserviceClient() {
        }
        
        public TemplateWebserviceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TemplateWebserviceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TemplateWebserviceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TemplateWebserviceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public InvokeWCFTest.ServiceReference1.Response GetTemplate(string templateNo, InvokeWCFTest.ServiceReference1.TemplateTagDataCollection tagDatas) {
            return base.Channel.GetTemplate(templateNo, tagDatas);
        }
        
        public System.Threading.Tasks.Task<InvokeWCFTest.ServiceReference1.Response> GetTemplateAsync(string templateNo, InvokeWCFTest.ServiceReference1.TemplateTagDataCollection tagDatas) {
            return base.Channel.GetTemplateAsync(templateNo, tagDatas);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InvokeWCFTest.ServiceReference1.GetTemplateInfoResponse InvokeWCFTest.ServiceReference1.ITemplateWebservice.GetTemplateInfo(InvokeWCFTest.ServiceReference1.GetTemplateInfoRequest request) {
            return base.Channel.GetTemplateInfo(request);
        }
        
        public InvokeWCFTest.ServiceReference1.Response GetTemplateInfo(string templateNo, out InvokeWCFTest.ServiceReference1.TemplateInfo templateInfo) {
            InvokeWCFTest.ServiceReference1.GetTemplateInfoRequest inValue = new InvokeWCFTest.ServiceReference1.GetTemplateInfoRequest();
            inValue.templateNo = templateNo;
            InvokeWCFTest.ServiceReference1.GetTemplateInfoResponse retVal = ((InvokeWCFTest.ServiceReference1.ITemplateWebservice)(this)).GetTemplateInfo(inValue);
            templateInfo = retVal.templateInfo;
            return retVal.GetTemplateInfoResult;
        }
        
        public System.Threading.Tasks.Task<InvokeWCFTest.ServiceReference1.GetTemplateInfoResponse> GetTemplateInfoAsync(InvokeWCFTest.ServiceReference1.GetTemplateInfoRequest request) {
            return base.Channel.GetTemplateInfoAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InvokeWCFTest.ServiceReference1.GetTemplateListResponse InvokeWCFTest.ServiceReference1.ITemplateWebservice.GetTemplateList(InvokeWCFTest.ServiceReference1.GetTemplateListRequest request) {
            return base.Channel.GetTemplateList(request);
        }
        
        public InvokeWCFTest.ServiceReference1.Response GetTemplateList(InvokeWCFTest.ServiceReference1.ProductType productType, InvokeWCFTest.ServiceReference1.TemplateType templateType, out InvokeWCFTest.ServiceReference1.TemplateInfo[] templateInfos) {
            InvokeWCFTest.ServiceReference1.GetTemplateListRequest inValue = new InvokeWCFTest.ServiceReference1.GetTemplateListRequest();
            inValue.productType = productType;
            inValue.templateType = templateType;
            InvokeWCFTest.ServiceReference1.GetTemplateListResponse retVal = ((InvokeWCFTest.ServiceReference1.ITemplateWebservice)(this)).GetTemplateList(inValue);
            templateInfos = retVal.templateInfos;
            return retVal.GetTemplateListResult;
        }
        
        public System.Threading.Tasks.Task<InvokeWCFTest.ServiceReference1.GetTemplateListResponse> GetTemplateListAsync(InvokeWCFTest.ServiceReference1.GetTemplateListRequest request) {
            return base.Channel.GetTemplateListAsync(request);
        }
        
        public bool Ping() {
            return base.Channel.Ping();
        }
        
        public System.Threading.Tasks.Task<bool> PingAsync() {
            return base.Channel.PingAsync();
        }
    }
}
